spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cigarcompendium?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: USERNAME
    password: PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  thymeleaf:
    cache: false
  flyway:
    enabled: false
  sql:
    init:
          mode: always
server:
  error:
    include-message: always

